version: "2"

services:
  redisc:
    build: ./redis
    tty: true
  d3ev:
    build: ./centos_compile
    tty: true
    volumes:
      - d3evroot:/root
      - codes:/ws

volumes:
  d3evroot:
  codes: