version: "2"

services:
  redisc:
    build: ./redis
    tty: true
    restart: always
  d3ev:
    build: ./centos_compile
    tty: true
    restart: always
    volumes:
      - d3evroot:/root
      - codes:/ws
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_USER: test
      MYSQL_ROOT_PASSWORD: test123
      MYSQL_DATABASE: cupd
    volumes:
      - db_persist:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - 5011:8080

volumes:
  d3evroot:
  codes:
  db_persist: