version: "2"

services:
  redis-cluster:
    build: ./redis
    ports:
      - "8101:8101"
      - "8102:8102"
      - "8103:8103"
      - "8104:8104"
      - "8105:8105"
      - "8106:8106"
  d3ev:
    build: ./centos_compile
    tty: true
    volumes:
      - d3evroot:/root
      - codes:/ws

volumes:
  d3evroot:
  codes: